default['wordpress']['site_url'] = 'http://192.168.56.99'
default['wordpress']['db_name'] = 'wordpress'
default['wordpress']['db_user'] = 'root'
default['wordpress']['db_password'] = ''
default['wordpress']['db_host'] = 'localhost'